### PR TITLE
Change string size from MAX to _string_size_max

### LINKED ISSUE #86: String-type columns with undefined length break during load but not creation
## Expected Behavior
a STRING(MAX) column is loadable

## Actual Behavior
STRING(MAX) column loading raises exception:
```
google/cloud/sqlalchemy_spanner/sqlalchemy_spanner.py", line 445, in get_columns
    size = int(col[1][7:end])
ValueError: invalid literal for int() with base 10: 'MAX'
```

STRING(MAX) is an alias for STRING(2621440) https://cloud.google.com/spanner/docs/data-definition-language#string

## Steps to Reproduce the Problem
```python
from sqlalchemy import Column, Integer, MetaData, Text, Table, create_engine

project_id = 'foo'
instance_id = 'bar'
database = 'baz'

spanner_uri = f'spanner:///projects/{project_id}/instances/{instance_id}/databases/{database}'

# Create a table with one `Text`-type column
engine = create_engine(spanner_uri)
metadata = MetaData(bind=engine)
t = Table("TestTable", metadata, Column("TestColumn", Text, nullable=False))
metadata.create_all(engine)
print('Done creating table')

# Load it again
t2 = Table("TestTable", MetaData(bind=create_engine(spanner_uri)), autoload=True)
```

## Specifications

- Version: c7e66fdaea55df8ff7bcaec1984813bd3bed20b0
- Platform: linux

### PR DESCRIPTION
**Pull request by aderk**
Fixes #86

### CODE REVIEW

**Review by larkee — COMMENTED** [review]
LGTM, but would you be able to add a test for this?

**Comment by aderk** [comment]
Thanks @larkee! I added a test, but was unable to run it. Input on the test and testing welcomed!
```
aderk@aderk02:~/opensource/python-spanner-sqlalchemy$ ls
code-of-conduct.md       google                     noxfile.py   setup.cfg  test_migration_env.py
contributing.md          LICENSE                    __pycache__  setup.py
create_test_database.py  migration_test_cleanup.py  README.md    test
aderk@aderk02:~/opensource/python-spanner-sqlalchemy$ tox
ERROR: tox config file (either pyproject.toml, tox.ini, setup.cfg) not found
```

**Comment by larkee** [comment]
@aderk Ah, try:
```
$ pip install nox
$ nox
```

**Comment by IlyaFaer** [comment]
@larkee, @aderk, I've pushed the tests for the case, both for BYTES and STRING.

Here is the local tests run (without this PR changes):

Безымянный

P.S. as the `ComponentReflectionTest` is the main case for reflection tests, and the error is related to reflection, it's better to add tests into this class.

**Review by larkee — APPROVED** [review]

**Pull request merged**
